config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'

  resources :pages

  get '/home' => 'pages#home'

  get '/profile' => 'pages#profile'

  get '/explore' => 'pages#explore'

  get '/settings' => 'pages#settings'

  get '/friends' => 'pages#friends'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def home
  end

  def profile
  end

  def explore
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">[ Flitter ]</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/home">Home <span class="sr-only">(current)</span></a></li>
        <li class = "active"><li><%= link_to "Featured" %><span class="sr-only">(current)</span></a></li>
        <li class = "active"><li><%= link_to "Sports" %><span class="sr-only">(current)</span></a></li>
        <li class = "active"><li><%= link_to "News" %><span class="sr-only">(current)</span></a></li>
        <li class = "active"><li><%= link_to "Music" %><span class="sr-only">(current)</span></a></li>
        <li class = "active"><li><%= link_to "Entertainment" %><span class="sr-only">(current)</span></a></li>
        <li class = "active"><li><%= link_to "Lifestyle" %><span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Welcome! <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">[ Flitter ]</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to "Home", home_path %></li>
        <li><%= link_to "Explore", explore_path %></li>

      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li><%= link_to "Edit", edit_user_registration_path %></li>
            <li><a href="/friends">Friends</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<!-- if a_user_signs_in
  then show user page
else
  show guest page
end -->



<% if user_signed_in? %>
  <%= render 'layouts/nav_user'%>
  <% else %>
  <%= render 'layouts/nav_guest'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/explore.html.erb
<h1>Pages#explore</h1>
<p>Find me in app/views/pages/explore.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <p>User</p>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <p>Trends</p>
      </div>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">

        <div class="form-group has-feedback">
          <!-- <label class="control-label">Username</label> -->
          <input type="text" class="form-control" placeholder="What's happening?" />
          <i class="button glyphicon glyphicon-camera form-control-feedback"></i>
        </div>
        <!-- <form class="navbar-form navbar-right">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
      </div>
      <div class="panel-body">
        Your timeline is currently empty.
      </div>
    </div>
  </div>
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <p>Who to Follow</p>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <p>About</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/profile.html.erb
<div class ="row">
  <div class="col-xs-12">
    <div class = "jumbotron">
      <h1>Username</h1>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-xs-3">

    <div class="panel panel-default">
      <div class="panel-body">
        <p>Fleets</p>
      </div>
    </div>
  </div>

  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        Your timeline is currently empty.
      </div>
    </div>
  </div>

  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <p>Who to Follow</p>
      </div>
    </div>
  </div>

  <div class="col-xs-3 col-xs-offset-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <p>Trends</p>
      </div>
    </div>
  </div>
</div>